- name: Upload to Puppet Forge API
        run: |
          TARBALL=$(ls pkg/*.tar.gz | head -n 1)
          echo "Uploading $TARBALL to Puppet Forge..."
          
          RESPONSE=$(curl -sS -X POST "https://forgeapi.puppet.com/v3/releases" \
            -H "Authorization: Bearer 4dbd7cc7a916a54b8fc88293087c54ba3d16cbe91d912866f3394356fcc9d7dc" \
            -F "file=@$TARBALL")
          
          echo "Server Response: $RESPONSE"
          
          if echo "$RESPONSE" | grep -q '"errors"'; then
            echo "Failed to publish!"
            exit 1
          fi
